# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Answrly Shopify Apps
email: support@doersoutdoors.com
description: >- # this means to ignore newlines until "baseurl:"
# What does it do?
- When you scroll a buy button becomes visible
- Has a buy button so customers can quickly add your product to cart
- Has a short description of the product.  
- Skip cart to go directly to checkout

# Why optimize your store for mobile shopping?

70% of all internet traffic is now mobile and if you are not optimizing your site for mobile use, you are losing money! Using the  button is a strategy that some of the best e-commerce retailers like amazon.com and alliexpress.com already using.

# How does a "Better Sticky Button" increase mobile conversions?

 This convenient placement puts the most important button in your store within thumb's reach at all times no matter where a customer is on the page.

Aside from being easier to reach while holding a mobile device, Better Sticky Button presents an opportunity for a customer to checkout when THEY are ready to.

No more guessing where to place your button or worrying about long product descriptions that take customers away from your button!


# Why Should I use it?
You want to make it as easy as possible for customers to make a sale
The app will pay for itself during the trial

Decreases friction
Your customers will love you
Customers can make faster decisions

# Features
- Reduced cart abandonment
 -Automatically matches your store theme and layout
- Matches your theme
- Tons of awesome animations
- Product review stars are shown in the bar
- No setup required
- Skip add to cart and go directly to checkout
- Enable and disable on mobile and desktop
- Change Buy Button text
- Set bar position to the top, left, bottom, and right
- Enable custom css
- 10 different button animations
- Show the quantity selected
- Show product variants
- Show compare at price
- Facebook pixel integration
- Google Analytics integration
- Format the price
- You can customize like crazy
- Enable custom styling
- Change your currency symbol
- Bar background color
- Button background color
- Bar text color
- Button text color
- Transparency of bar
- Fade in effects (ie how far down the page you want it to scroll in)

# Works Straight out of the box:
- Simply install and Use
- No need to change or modify your theme
- No need to add any coding (unless you want to)
- No need to configure or setup
- No need to pay for 3rd party installation support

# Tested with all of Shopify's Free Themes:
- Boundless
- Brooklyn
- Debut
- Jumpstart
- Minimal
- Narrative
- Pop
- Simple
- Supply
- Venture
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
